import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    // Cleanup is the runner's job: a stub that outlives its test makes a later
    // failure a mystery in another file.
    restoreMocks: true,
    clearMocks: true,
    unstubEnvs: true,
    unstubGlobals: true,
    // A focused test silently shrinks the suite; fail on it everywhere.
    allowOnly: false,
    projects: [
      {
        extends: true,
        plugins: [react()],
        test: {
          name: "ui",
          environment: "jsdom",
          include: ["ui/src/**/*.test.{ts,tsx}"],
          setupFiles: ["ui/src/test/setup.ts"],
          // Vitest stubs CSS by default; the contrast test reads tokens.css as text.
          css: { include: [/tokens\.css/] },
          testTimeout: 10_000,
        },
      },
      {
        extends: true,
        test: {
          name: "scripts",
          environment: "node",
          include: ["scripts/**/*.test.ts"],
          exclude: ["**/fixtures/**"],
          testTimeout: 60_000,
        },
      },
    ],
    coverage: {
      provider: "v8",
      reportsDirectory: "coverage",
      reporter: ["text", "lcov"],
      // Every source file counts, tested or not, so an untested module shows as 0%.
      include: ["ui/src/**/*.{ts,tsx}", "scripts/**/*.ts"],
      exclude: [
        "**/*.test.{ts,tsx}",
        "**/fixtures/**",
        "ui/src/test/**",
        // Generated by ts-rs from core's Rust types (`just bindings`); tested there.
        "ui/src/ipc/generated/**",
        // The React entry point: mounts the app into index.html, nothing to decide.
        "ui/src/main.tsx",
        // Type declarations only.
        "**/*.d.ts",
      ],
      // Per-glob floors, never one combined number, so one tree cannot subsidise
      // another (typescript-template's pattern; design D13).
      thresholds: {
        "ui/src/**": { lines: 80, functions: 80 },
        // Every repository script; scripts/lib/guard/** also counts here.
        "scripts/**": { lines: 85, functions: 90 },
        // The credential and path rules of the staged guard: the most security-critical
        // code in the repository, so a higher floor.
        "scripts/lib/guard/**": { lines: 90, functions: 100 },
      },
    },
  },
});
